### ISSUE TITLE
Changelog : Any breaking changes from v3.1.0 to v5 ?

### ISSUE THREAD

**Issue by laurent-d** [aullman/opentok-layout-js#122]
Hi @aullman,

Thanks for the amazing job on this lib :)
Is there more things to know before upgrading from v3 to v5 ? the changelog is quiet light :p 

Have a good day

**Comment by aullman** [comment]
Sorry for the late response. I had to go back and have a look at the diffs. 

It looks like from v3 to v4 we started taking margin into account on the elements. Before then it ignored the margin. So this could be a breaking change for some.

From v4 to v5 we added the areas in the response to `getLayout`. So instead of just returning the array of boxes, it now returns an object with a `boxes` property which is the same as the original array of boxes and also an `areas` property which tells you about the dimensions of the small and big area. 

I hope that helps!
