### ISSUE TITLE
opentok-react styling and demo functionality

### ISSUE THREAD

**Issue by RTay385** [aullman/opentok-layout-js#61]
Im trying to get the functionality of your demo where I can click a subscriber or publisher and have it become big and have the others go to the right side. I've followed your guidelines to the point where the sub streams will appear in a container. I'm looking at issue #52 for reference. Is there any example code we can see for your demo?

**Comment by sweeetland** [comment]
I agree would be very helpful.

**Comment by aullman** [comment]
The example code for the demo is [here](https://github.com/aullman/opentok-layout-js/blob/master/index.html)

It's not in React though, it's just vanilla JS. In your case I guess you want to keep track of which stream should be big. I would add a property to the stream maybe which is `big`. Then listen for click events and modify the streams so that the right one is `big`. Then re-render the component. I hope that makes sense.
