### ISSUE TITLE
Padding Around Video Elements

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [aullman/opentok-layout-js#87]
Hello, big fan of this library.

So one thing that is common in mainstream video applications is padding between video elements. See here 
![image](https://user-images.githubusercontent.com/16419696/121739986-a7541c80-cab9-11eb-8cd8-56e0dbec6164.png).

One thing that I think could be possible with this library is to have a variable padding option (default 0) that puts this padding on elements to give them a more spaced look. 

I would be happy to do the work and put in a PR, I'm just a bit lost when I'm looking at the code. Would it be possible to work with you on this to get the feature merged?

**Comment by aullman** [comment]
It turned out that this was actually [a bug](https://github.com/aullman/opentok-layout-js/issues/90). The layout should respect the padding and margins of the elements inside it. So if you just put eg. margin: 5px on each of the elements you would end up with something like your image above. This is now fixed in v4.0.0.
